org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)
forge_version=36.2.39
forge_version_range=[36,)
loader_version_range=[36,)
mapping_channel=official
mapping_version=1.16.5

mod_id=mobends
mod_name=Mo' Bends (Reforged)
mod_version=1.16.5-1.0.0
mod_group=com.thatsoulyguy
mod_license=MIT
mod_authors=Astryxion
mod_credits=GoblinBob, Sxilverr, ThatSoulyGuy
mod_homepage=https://github.com/astryxion/MoBends-Reforged
mod_description=If you think that Minecraft characters could be more realistic, instead of steady and rigid animations, this mod is just for you! It makes players seem alive, and adds epic sword animations!
